---
# tasks file for gitlab instance
- name: Updating current APT cache.
  apt:
    update_cache: yes
  tags:
    - apt
    - software

- name: Run Gitlab script
  ansible.builtin.script: installers/gitlab.sh {{ gitlab_url }}
  ignore_errors: true

- name: Create gitlab.rb from template
  ansible.builtin.template:
    src: templates/gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
